# ===== NETLIFY CONFIGURATION FOR VINO K PORTFOLIO =====

[build]
  # Build command (not needed for static site)
  command = "echo 'Building Vino K Portfolio...'"
  
  # Directory to publish - THIS IS THE KEY FIX!
  publish = "client"
  
  # Functions directory (if using Netlify Functions)
  functions = "netlify/functions"

[build.environment]
  # Environment variables for build process
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# ===== REDIRECTS AND REWRITES =====

# SPA fallback - redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to backend (when backend is deployed)
[[redirects]]
  from = "/api/*"
  to = "https://vino-k-portfolio-api.onrender.com/api/:splat"
  status = 200
  force = true

# Redirect old portfolio URLs
[[redirects]]
  from = "/old-portfolio/*"
  to = "/"
  status = 301

# ===== HEADERS =====

[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ===== FORM HANDLING =====

# Contact form submission (fallback if backend is not available)
[[forms]]
  name = "contact"
  action = "/thank-you"
  method = "POST"

# ===== CONTEXT-SPECIFIC SETTINGS =====

# Production settings
[context.production]
  command = "echo 'Production build complete'"
  
  [context.production.environment]
    NODE_ENV = "production"
    API_URL = "https://vino-k-portfolio-api.onrender.com"

# Deploy preview settings
[context.deploy-preview]
  command = "echo 'Deploy preview build'"
  
  [context.deploy-preview.environment]
    NODE_ENV = "staging"

# Development settings
[context.dev]
  command = "echo 'Development build'"
  
  [context.dev.environment]
    NODE_ENV = "development"
    API_URL = "http://localhost:5000"

# ===== PROCESSING =====

# Image optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
