// ===== PROJECTS DATA =====
// All GitHub repositories for Vino K (K-vino)

const projectsData = {
    profile: {
        username: "K-vino",
        displayName: "Vino k",
        description: "Data Science & AI Enthusiast | Learning Path in Data Analysis | YouTuber Sharing My Journey",
        githubUrl: "https://github.com/K-vino",
        stats: {
            repositories: 46,
            stars: 2,
            followers: 3,
            following: 1
        }
    },
    
    repositories: [
        // Featured/Main Projects
        {
            id: "my-portfolio-website",
            name: "MY_PORTFOLIO_WEBSITE",
            description: "Full-stack portfolio website showcasing my journey as an AIML Developer, Data Scientist, and Cloud Engineer. Built with modern web technologies.",
            language: "HTML",
            languageColor: "#e34c26",
            stars: 0,
            forks: 0,
            updated: "2 minutes ago",
            status: "public",
            category: "featured",
            tags: ["portfolio", "web-development", "full-stack"],
            githubUrl: "https://github.com/K-vino/MY_PORTFOLIO_WEBSITE",
            liveUrl: "https://vinok.netlify.app",
            license: null,
            isForked: false
        },
        {
            id: "ai-meeting-companion",
            name: "ai-meeting-companion",
            description: "Problem: People forget key points during online meetings. Solution: An extension that automatically detects Zoom/Google Meet/MS Teams tabs, listens in (with user consent), and generates live meeting summaries.",
            language: "TypeScript",
            languageColor: "#3178c6",
            stars: 0,
            forks: 0,
            updated: "3 days ago",
            status: "public",
            category: "featured",
            tags: ["ai", "browser-extension", "meeting-assistant"],
            githubUrl: "https://github.com/K-vino/ai-meeting-companion",
            license: "MIT",
            isForked: false
        },
        {
            id: "hr-chatbot",
            name: "HR-chatbot",
            description: "An LLM-powered HR chatbot that helps employees ask HR-related questions by referencing internal policy documents, employee handbooks, and company guidelines using RAG (Retrieval-Augmented Generation).",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "last week",
            status: "public",
            category: "featured",
            tags: ["ai", "chatbot", "rag", "hr"],
            githubUrl: "https://github.com/K-vino/HR-chatbot",
            license: null,
            isForked: false
        },
        {
            id: "ml-projects-portfolio",
            name: "ml-projects-portfolio",
            description: "12 Machine Learning Projects | Beginner to Expert | End-to-End Jupyter Notebooks, EDA, Model Building, Evaluation & Deployment",
            language: "Jupyter Notebook",
            languageColor: "#DA5B0B",
            stars: 0,
            forks: 0,
            updated: "Jul 6",
            status: "public",
            category: "featured",
            tags: ["machine-learning", "data-science", "jupyter"],
            githubUrl: "https://github.com/K-vino/ml-projects-portfolio",
            license: null,
            isForked: false
        },
        {
            id: "deep-learning-projects-collection",
            name: "deep-learning-projects-collection",
            description: "A curated collection of 12 deep learning projects, ranging from beginner to expert level, covering CNNs, RNNs, Transformers, GANs, and more. Ideal for hands-on learning and portfolio building.",
            language: "Jupyter Notebook",
            languageColor: "#DA5B0B",
            stars: 0,
            forks: 0,
            updated: "Jul 6",
            status: "public",
            category: "featured",
            tags: ["deep-learning", "neural-networks", "ai"],
            githubUrl: "https://github.com/K-vino/deep-learning-projects-collection",
            license: null,
            isForked: false
        },
        {
            id: "ai-resume-analyzer-project",
            name: "AI-Resume-Analyzer-Project",
            description: "An AI-powered tool that analyzes resumes and gives insights like skills match, job fit, and recommendations using NLP and machine learning.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Jun 21",
            status: "public",
            category: "featured",
            tags: ["ai", "nlp", "resume-analysis"],
            githubUrl: "https://github.com/K-vino/AI-Resume-Analyzer-Project",
            license: null,
            isForked: false
        },

        // Web Development Projects
        {
            id: "task-1-frontend-internship-emptycup",
            name: "TASK-1-Frontend-Internship-EmptyCup",
            description: "Task 1 assignment submission for Frontend Development Internship at EmptyCup – A 3D Solar System Simulation built using Three.js",
            language: "JavaScript",
            languageColor: "#f1e05a",
            stars: 0,
            forks: 0,
            updated: "Jul 3",
            status: "public",
            category: "web",
            tags: ["threejs", "3d", "solar-system", "internship"],
            githubUrl: "https://github.com/K-vino/TASK-1-Frontend-Internship-EmptyCup",
            license: null,
            isForked: false
        },
        {
            id: "interior-connect",
            name: "interior-connect",
            description: "Platform connecting interior designers with clients, featuring portfolio showcases and project management tools.",
            language: "TypeScript",
            languageColor: "#3178c6",
            stars: 0,
            forks: 0,
            updated: "May 25",
            status: "public",
            category: "web",
            tags: ["interior-design", "platform", "typescript"],
            githubUrl: "https://github.com/K-vino/interior-connect",
            license: null,
            isForked: false
        },
        {
            id: "culture-tech-ai",
            name: "Culture_tech_AI",
            description: "An AI-powered cultural assistant platform to connect, chat, and collaborate with people to improve and explore local and global cultures.",
            language: "HTML",
            languageColor: "#e34c26",
            stars: 0,
            forks: 0,
            updated: "May 24",
            status: "public",
            category: "web",
            tags: ["culture", "ai", "social-platform"],
            githubUrl: "https://github.com/K-vino/Culture_tech_AI",
            license: null,
            isForked: false
        },
        {
            id: "bookmyshow-mystyle",
            name: "BookMyShow-Mystyle-",
            description: "Custom-styled BookMyShow clone with enhanced UI/UX and additional features for movie booking.",
            language: "HTML",
            languageColor: "#e34c26",
            stars: 0,
            forks: 0,
            updated: "Oct 14, 2024",
            status: "public",
            category: "web",
            tags: ["clone", "booking", "movies"],
            githubUrl: "https://github.com/K-vino/BookMyShow-Mystyle-",
            license: null,
            isForked: false
        },
        {
            id: "dashboard",
            name: "dashboard",
            description: "Interactive dashboard for data visualization and analytics with real-time updates and customizable widgets.",
            language: "JavaScript",
            languageColor: "#f1e05a",
            stars: 0,
            forks: 0,
            updated: "Sep 8, 2024",
            status: "public",
            category: "web",
            tags: ["dashboard", "data-visualization", "analytics"],
            githubUrl: "https://github.com/K-vino/dashboard",
            license: null,
            isForked: false
        },

        // AI/ML Projects
        {
            id: "loan-default-prediction-app",
            name: "loan-default-prediction-app",
            description: "🏦 Predict loan approvals using Machine Learning",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Jul 2",
            status: "public",
            category: "ai-ml",
            tags: ["machine-learning", "finance", "prediction"],
            githubUrl: "https://github.com/K-vino/loan-default-prediction-app",
            license: null,
            isForked: false
        },
        {
            id: "promptgpt-suite-vmd",
            name: "promptgpt-suite-vmd",
            description: "Comprehensive suite of AI prompt engineering tools and utilities for enhanced GPT interactions and productivity.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Jun 23",
            status: "public",
            category: "ai-ml",
            tags: ["gpt", "prompt-engineering", "ai-tools"],
            githubUrl: "https://github.com/K-vino/promptgpt-suite-vmd",
            license: null,
            isForked: false
        },
        {
            id: "ai-resume-analyzer",
            name: "AI-RESUME-ANALYZER",
            description: "An AI-powered resume analyzer and interview scheduler built with Streamlit. This project automatically extracts candidate details, matches resumes with job descriptions, shortlists candidates using advanced algorithms.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Apr 13",
            status: "public",
            category: "ai-ml",
            tags: ["ai", "resume", "streamlit", "hr"],
            githubUrl: "https://github.com/K-vino/AI-RESUME-ANALYZER",
            license: null,
            isForked: false
        },
        {
            id: "vmd-ai-app",
            name: "VMD-AI-APP",
            description: "VMD-specific AI application with custom algorithms and specialized functionality for data processing.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Oct 30, 2024",
            status: "public",
            category: "ai-ml",
            tags: ["ai", "data-processing", "algorithms"],
            githubUrl: "https://github.com/K-vino/VMD-AI-APP",
            license: null,
            isForked: false
        },
        {
            id: "ai-app",
            name: "AI-APP",
            description: "General-purpose AI application with multiple AI model integrations and user-friendly interface.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Nov 6, 2024",
            status: "public",
            category: "ai-ml",
            tags: ["ai", "multi-model", "interface"],
            githubUrl: "https://github.com/K-vino/AI-APP",
            license: null,
            isForked: false
        },
        {
            id: "aiml-ds",
            name: "AIML-DS",
            description: "Comprehensive collection of AI, Machine Learning, and Data Science projects with tutorials and implementations.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Sep 15, 2024",
            status: "public",
            category: "ai-ml",
            tags: ["ai", "machine-learning", "data-science"],
            githubUrl: "https://github.com/K-vino/AIML-DS",
            license: null,
            isForked: false
        },

        // System/Management Projects
        {
            id: "smart-x",
            name: "SMART-X",
            description: "Smart automation platform integrating IoT devices, AI analytics, and intelligent decision-making systems.",
            language: "TypeScript",
            languageColor: "#3178c6",
            stars: 0,
            forks: 0,
            updated: "Apr 23",
            status: "public",
            category: "system",
            tags: ["iot", "automation", "smart-systems"],
            githubUrl: "https://github.com/K-vino/SMART-X",
            license: null,
            isForked: false
        },
        {
            id: "attendance",
            name: "Attendance",
            description: "Attendance management system with automated tracking, reporting, and integration capabilities.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Sep 4, 2024",
            status: "public",
            category: "system",
            tags: ["attendance", "management", "tracking"],
            githubUrl: "https://github.com/K-vino/Attendance",
            license: null,
            isForked: false
        },

        // Voting/Civic Projects
        {
            id: "admin-vote-complaint",
            name: "ADMIN_VOTE_complaint",
            description: "Administrative interface for managing voting complaints and election-related issues with dashboard analytics.",
            language: "HTML",
            languageColor: "#e34c26",
            stars: 0,
            forks: 0,
            updated: "May 6",
            status: "public",
            category: "civic",
            tags: ["voting", "admin", "complaints"],
            githubUrl: "https://github.com/K-vino/ADMIN_VOTE_complaint",
            license: null,
            isForked: false
        },
        {
            id: "voting-issue-complaint-form",
            name: "voting-issue-complaint-form",
            description: "Web form for citizens to report voting issues and election complaints with automated routing and tracking.",
            language: "HTML",
            languageColor: "#e34c26",
            stars: 0,
            forks: 0,
            updated: "May 6",
            status: "public",
            category: "civic",
            tags: ["voting", "complaints", "forms"],
            githubUrl: "https://github.com/K-vino/voting-issue-complaint-form",
            license: null,
            isForked: false
        },
        {
            id: "complaint-vote",
            name: "complaint_vote",
            description: "Complaint management system for voting and election-related issues with real-time tracking and resolution.",
            language: "HTML",
            languageColor: "#e34c26",
            stars: 0,
            forks: 0,
            updated: "May 6",
            status: "public",
            category: "civic",
            tags: ["complaints", "voting", "management"],
            githubUrl: "https://github.com/K-vino/complaint_vote",
            license: null,
            isForked: false
        },

        // Data Projects
        {
            id: "data-contract",
            name: "data_contract",
            description: "Data contract management system for ensuring data quality, governance, and compliance across organizations.",
            language: "HTML",
            languageColor: "#e34c26",
            stars: 0,
            forks: 0,
            updated: "Apr 30",
            status: "public",
            category: "data",
            tags: ["data-governance", "contracts", "compliance"],
            githubUrl: "https://github.com/K-vino/data_contract",
            license: null,
            isForked: false
        },
        {
            id: "dash",
            name: "dash",
            description: "Dashboard application with interactive components and real-time data visualization capabilities.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Aug 9, 2024",
            status: "public",
            category: "data",
            tags: ["dashboard", "visualization", "dash"],
            githubUrl: "https://github.com/K-vino/dash",
            license: null,
            isForked: false
        },
        {
            id: "data",
            name: "Data",
            description: "Data processing and analysis tools with various utilities for data manipulation and visualization.",
            language: "CSS",
            languageColor: "#563d7c",
            stars: 0,
            forks: 0,
            updated: "Aug 7, 2024",
            status: "public",
            category: "data",
            tags: ["data-processing", "analysis", "tools"],
            githubUrl: "https://github.com/K-vino/Data",
            license: null,
            isForked: false
        },
        {
            id: "forage-walmart-task-4",
            name: "forage-walmart-task-4",
            description: "Forked from theforage/forage-walmart-task-4. Task 4 starter repo for Walmart Forage program focusing on data analysis and business intelligence.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Sep 17, 2024",
            status: "public",
            category: "data",
            tags: ["walmart", "forage", "data-analysis"],
            githubUrl: "https://github.com/K-vino/forage-walmart-task-4",
            license: null,
            isForked: true
        },

        // Forked/Learning Projects
        {
            id: "llmware-unstop-git-together",
            name: "llmware_unstop_Git_Together",
            description: "Forked from llmware-ai/llmware. Unified framework for building enterprise RAG pipelines with small, specialized models",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Apr 11",
            status: "public",
            category: "ai-ml",
            tags: ["rag", "llm", "enterprise"],
            githubUrl: "https://github.com/K-vino/llmware_unstop_Git_Together",
            license: "Apache License 2.0",
            isForked: true
        },
        {
            id: "drag-and-drop",
            name: "Drag-and-Drop",
            description: "Forked from TechWithEmmaYT/Advanced-AI-Formy-Builder-Drag-n-Drop. Advanced AI-powered form builder with drag-and-drop interface.",
            language: "TypeScript",
            languageColor: "#3178c6",
            stars: 0,
            forks: 0,
            updated: "Apr 1",
            status: "public",
            category: "web",
            tags: ["drag-drop", "form-builder", "ai"],
            githubUrl: "https://github.com/K-vino/Drag-and-Drop",
            license: "Other",
            isForked: true
        },
        {
            id: "ollama-resume-analyser",
            name: "ollama_resume_analyser",
            description: "Forked from Akhil-Pratyush-Tadanki/ollama_resume_analyser. AI-powered text analysis agent, designed to help job seekers by analysing job descriptions and resumes.",
            language: "Jupyter Notebook",
            languageColor: "#DA5B0B",
            stars: 0,
            forks: 0,
            updated: "May 10, 2024",
            status: "public",
            category: "ai-ml",
            tags: ["resume", "analysis", "ollama"],
            githubUrl: "https://github.com/K-vino/ollama_resume_analyser",
            license: null,
            isForked: true
        },
        {
            id: "web-dev-projects-idea",
            name: "Web-Dev-Projects-Idea",
            description: "Forked from s-shemmee/Web-Dev-Projects-Idea. 40+ web development projects that gonna help you to improve your self in HTML, CSS and JavaScript all in this repository.",
            language: "JavaScript",
            languageColor: "#f1e05a",
            stars: 1,
            forks: 0,
            updated: "Jul 21, 2023",
            status: "public",
            category: "web",
            tags: ["web-development", "projects", "learning"],
            githubUrl: "https://github.com/K-vino/Web-Dev-Projects-Idea",
            license: "MIT",
            isForked: true
        },
        {
            id: "ui-ai",
            name: "UI_AI",
            description: "Forked from mars9541/website-editor. Wonderful drag and drop website builder with AI-powered design suggestions.",
            language: "JavaScript",
            languageColor: "#f1e05a",
            stars: 0,
            forks: 0,
            updated: "Jun 18, 2023",
            status: "public",
            category: "web",
            tags: ["ui", "ai", "website-builder"],
            githubUrl: "https://github.com/K-vino/UI_AI",
            license: "Apache License 2.0",
            isForked: true
        },

        // Personal/Config Projects
        {
            id: "k-vino",
            name: "K-vino",
            description: "Config files for my GitHub profile.",
            language: "Config",
            languageColor: "#6f42c1",
            stars: 0,
            forks: 0,
            updated: "Sep 10, 2023",
            status: "public",
            category: "config",
            tags: ["github-config", "profile"],
            githubUrl: "https://github.com/K-vino/K-vino",
            license: null,
            isForked: false
        },
        {
            id: "about-me",
            name: "About-ME",
            description: "Personal profile and portfolio showcase with interactive elements and dynamic content management.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Nov 9, 2024",
            status: "public",
            category: "portfolio",
            tags: ["portfolio", "personal", "profile"],
            githubUrl: "https://github.com/K-vino/About-ME",
            license: null,
            isForked: false
        },
        {
            id: "web",
            name: "web",
            description: "General web development projects and experiments with modern web technologies and frameworks.",
            language: "HTML",
            languageColor: "#e34c26",
            stars: 0,
            forks: 0,
            updated: "Sep 2, 2024",
            status: "public",
            category: "web",
            tags: ["web-development", "experiments"],
            githubUrl: "https://github.com/K-vino/web",
            license: null,
            isForked: false
        },
        {
            id: "culture-tech",
            name: "Culture_tech",
            description: "Technology platform for cultural exchange, language learning, and cross-cultural communication.",
            language: "JavaScript",
            languageColor: "#f1e05a",
            stars: 0,
            forks: 0,
            updated: "Apr 18",
            status: "public",
            category: "social",
            tags: ["culture", "technology", "communication"],
            githubUrl: "https://github.com/K-vino/Culture_tech",
            license: null,
            isForked: false
        },

        // Private Projects (limited info)
        {
            id: "empath-voices-rising",
            name: "empath-voices-rising",
            description: "Platform for empowering voices and building community connections through technology and social impact.",
            language: "TypeScript",
            languageColor: "#3178c6",
            stars: 0,
            forks: 0,
            updated: "Jun 24",
            status: "private",
            category: "social",
            tags: ["social-impact", "community"],
            githubUrl: "https://github.com/K-vino/empath-voices-rising",
            license: null,
            isForked: false
        },
        {
            id: "ai-prompt-assistant-web-app",
            name: "AI-Prompt-Assistant-Web-App",
            description: "Web application for AI prompt assistance and optimization, helping users create better prompts for various AI models.",
            language: "JavaScript",
            languageColor: "#f1e05a",
            stars: 0,
            forks: 0,
            updated: "Jun 23",
            status: "private",
            category: "ai-ml",
            tags: ["ai", "prompts", "web-app"],
            githubUrl: "https://github.com/K-vino/AI-Prompt-Assistant-Web-App",
            license: null,
            isForked: false
        },
        {
            id: "tech-career-forge",
            name: "tech-career-forge",
            description: "Career development platform for tech professionals with skill assessments, learning paths, and job matching.",
            language: "TypeScript",
            languageColor: "#3178c6",
            stars: 0,
            forks: 0,
            updated: "May 19",
            status: "private",
            category: "career",
            tags: ["career", "tech", "platform"],
            githubUrl: "https://github.com/K-vino/tech-career-forge",
            license: null,
            isForked: false
        },
        {
            id: "account-hub-lite",
            name: "account-hub-lite",
            description: "Lightweight account management system with user authentication, profile management, and security features.",
            language: "TypeScript",
            languageColor: "#3178c6",
            stars: 0,
            forks: 0,
            updated: "May 11",
            status: "private",
            category: "system",
            tags: ["authentication", "account-management"],
            githubUrl: "https://github.com/K-vino/account-hub-lite",
            license: null,
            isForked: false
        },
        {
            id: "digital-election-pulse",
            name: "digital-election-pulse",
            description: "Digital platform for election monitoring, voter engagement, and democratic participation analytics.",
            language: "TypeScript",
            languageColor: "#3178c6",
            stars: 0,
            forks: 0,
            updated: "May 6",
            status: "private",
            category: "civic",
            tags: ["election", "monitoring", "democracy"],
            githubUrl: "https://github.com/K-vino/digital-election-pulse",
            license: null,
            isForked: false
        },
        {
            id: "swift-goal-nexus",
            name: "swift-goal-nexus",
            description: "Goal tracking and achievement platform with AI-powered insights and productivity analytics.",
            language: "TypeScript",
            languageColor: "#3178c6",
            stars: 0,
            forks: 0,
            updated: "May 2",
            status: "private",
            category: "productivity",
            tags: ["goals", "productivity", "tracking"],
            githubUrl: "https://github.com/K-vino/swift-goal-nexus",
            license: null,
            isForked: false
        },
        {
            id: "vegamai-website-launchpad",
            name: "vegamai-website-launchpad",
            description: "Website launchpad platform for AI startups with templates, deployment tools, and marketing automation.",
            language: "TypeScript",
            languageColor: "#3178c6",
            stars: 0,
            forks: 0,
            updated: "Apr 27",
            status: "private",
            category: "startup",
            tags: ["startup", "launchpad", "ai"],
            githubUrl: "https://github.com/K-vino/vegamai-website-launchpad",
            license: null,
            isForked: false
        },
        {
            id: "job",
            name: "JOB",
            description: "Job search and career management platform with AI-powered job matching and application tracking.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Apr 4",
            status: "private",
            category: "career",
            tags: ["job-search", "career", "ai"],
            githubUrl: "https://github.com/K-vino/JOB",
            license: null,
            isForked: false
        },
        {
            id: "g",
            name: "g",
            description: "Private project with specialized functionality and custom implementations.",
            language: "JavaScript",
            languageColor: "#f1e05a",
            stars: 0,
            forks: 0,
            updated: "Sep 2, 2024",
            status: "private",
            category: "misc",
            tags: ["private", "custom"],
            githubUrl: "https://github.com/K-vino/g",
            license: null,
            isForked: false
        },
        {
            id: "sih",
            name: "sih",
            description: "Smart India Hackathon project with innovative solutions for national challenges.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Sep 1, 2024",
            status: "private",
            category: "hackathon",
            tags: ["hackathon", "india", "innovation"],
            githubUrl: "https://github.com/K-vino/sih",
            license: null,
            isForked: false
        },
        {
            id: "github",
            name: "github",
            description: "GitHub-related tools and utilities for repository management and automation.",
            language: "Python",
            languageColor: "#3776ab",
            stars: 0,
            forks: 0,
            updated: "Sep 14, 2023",
            status: "private",
            category: "tools",
            tags: ["github", "automation", "tools"],
            githubUrl: "https://github.com/K-vino/github",
            license: null,
            isForked: false
        }
    ]
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = projectsData;
}
